### ISSUE TITLE
Won't work in TextWrangler

### ISSUE THREAD

**Issue by jbwhaley** [dunn/fountain-clm#2]
It doesn't seem to work at all on either my desktop or my laptop--one is running Mountain Lion and the other is running Lion. My copies of TextWrangler are from the Mac App Store...could this be a sandboxing issue?

**Comment by dunn** [comment]
It's working for me in TextWrangler (both from the App Store and not), so could you post the text of the .fountain file you're using?  (Here, or in a [gist](http://gist.github.com) if it's long.)

**Comment by jbwhaley** [comment]
Thanks for your help--text below. (This is just a goofy bit of text I wrote
up for testing; pretty weird. Hopefully good for a laugh).

INT. HOUSE - DAY

Bob, smacking his lips:

BOB
There's extra butter today!

NED
Why?

BOB
Because God is good!

EXT. PARKING LOT - NIGHT

Bob and Ned are eating six pounds of butter.

BOB
Nomnomnom

NED
Numnumnum

**Comment by dunn** [comment]
The first scene doesn't fold unless there's a blank line above it (which definitely needs to be fixed), but otherwise that snippet works OK for me.  If you've got "Fountain" selected as your document language and are getting no syntax highlighting or folding at all, then I'm at a bit of a loss.

**Comment by jbwhaley** [comment]
The problem is that "Fountain" does not even show up as an option when it comes to language selection. So: nothing folds, nothing is highlighted.

**Comment by dunn** [comment]
Bizarre.  All I can think of at the moment is that you might have installed fountain-clm.plist in the wrong directory.  It should be placed in the user directory `~/Library/Application Support/TextWrangler/Language Modules/`, not the system-wide `/Library/Application Support/...`.

**Comment by jbwhaley** [comment]
Nope, it's definitely in ~/Library/...etc. Weird.

**Comment by jbwhaley** [comment]
Anyone else having this problem? It's driving me crazy.

**Comment by dunn** [comment]
I'm not sure if either of these actions will help, but you could try
1. Installing a non-App Store version of TextWrangler; or
2. Having `/Applications/Utilities/Console` open when you try to open a `.fountain` file, and see if Console logs any TextWrangler error messages.

**Comment by jbwhaley** [comment]
Ah. Here we go. Any ideas?

Aug 26 15:18:37 BIG-MAC.local TextWrangler[28713]: The following problem(s) were encountered while loading the language module at /Users/jbwhaley/Library/Application Support/TextWrangler/Language Modules/fountain-clm.plist:
Aug 26 15:18:37 BIG-MAC.local TextWrangler[28713]:  BBLMColorsSyntax and BBLMScansFunctions were both missing.
Aug 26 15:18:37 BIG-MAC.local TextWrangler[28713]:  BBLMLanguageCode key is missing, or longer than four characters.
Aug 26 15:18:37 BIG-MAC.local TextWrangler[28713]:  BBLMLanguageDisplayName is missing, or is zero length.
Aug 26 15:18:37 BIG-MAC.local TextWrangler[28713]:  The Language Features key is missing.
Aug 26 15:18:37 BIG-MAC.local TextWrangler[28713]: The reported problems will prevent the language module from loading.
                "_CFURLString" = "/Applications/TextWrangler.app";
        ApplicationId = "com.barebones.textwrangler";
        ApplicationName = TextWrangler;

**Comment by dunn** [comment]
That's interesting, because the keys that it says are missing are definitely in fountain-clm.plist; you can see them if you look at the [source](https://github.com/grumble/fountain-clm/blob/master/fountain-clm.plist).  Maybe your version got corrupted somehow?  Try downloading it again, make sure that the downloaded file matches the file hosted here on GitHub, and re-install it.

**Comment by jbwhaley** [comment]
I finally got it to work by pasting the source directly into the .plist file. Not sure what happened, but it's all resolved now. Thanks for your help.

**Comment by dunn** [comment]
Great!  Sorry this took so long to resolve.
