### ISSUE TITLE
Not working in latest BBEdit Update

### ISSUE THREAD

**Issue by kaapow** [dunn/fountain-clm#4]
Hi there, just noticed that this stopped working in the latest BBEdit update (10.5). 

Actually it's only partially broken, some things are highlighted (title information at the top of a script), but not everything (dialogue, scenes, etc).

**Comment by dunn** [comment]
I mentioned this on Twitter ages ago, but it should be written down here:  unfortunately I don't actually have BBEdit; I've been testing on TextWrangler.  So until TW is updated (and breaks in the same way!), I'm not sure what I can do about this.  Sorry!

**Comment by dunn** [comment]
Well, TextWrangler just got updated, and I was hoping that would bring its behavior in line with BBEdit, but things still look OK to me.  Are you still having problems?  If so, can you get me a gist of the misbehaving Fountain file?

**Comment by dunn** [comment]
I dunno why I didn't just download the trial version of BBEdit until now, maybe I thought I had to buy it through the app store who knows! Anyway I'm not seeing problems w/ non-app store BBEdit 10.5.8
